[package]
name = "collatz_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.16"
csv = "1.3.0"
itertools = "0.13.0"
rayon = "1.10.0"
rug = "1.26.0"
serde = {version = "1.0.204", features = ["derive"]}
